version: '3.8'

services:
  db:
    build: ./server/database/.
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
    # TODO: remove or refactor for production
    # those are used just for hot reolad and
    # node modules caching
    volumes:
      - source: ./server
        target: /kashafty/server
        type: bind
      - source: ./client
        target: /kashafty/client
        type: bind
      - source: ./node_modules
        target: /kashafty/node_modules
        type: bind
      - source: ./client/node_modules
        target: /kashafty/client/node_modules
        type: bind
